#!/bin/bash

set -euo pipefail

# wp-db-restore.sh
# Restores a WordPress database from a selected SQL file in the current directory.

SCRIPTPATH=$(dirname "$0")
# Source common logic
source "$SCRIPTPATH/common.sh"

echo -e "${BLUE}"
echo "+---------------------+"
echo "|   WP DB Restore     |"
echo "+---------------------+"
echo -e "${NC}"

if [ ! -f "wp-config.php" ]; then
  echo -e "${RED}ERROR: No wp-config.php found.${NC}"
  echo "Execute this script in the WordPress root."
  exit 1
fi

# 1. Read Credentials
get_db_credentials_from_config
MYSQL_OPTS=$(get_mysql_opts)

# 2. List SQL files
echo "Searching for .sql and .sql.gz files..."
# Enable nullglob to handle empty matches gracefully
shopt -s nullglob
sql_files=(*.sql *.sql.gz)
shopt -u nullglob

if [ ${#sql_files[@]} -eq 0 ]; then
    echo -e "${YELLOW}No .sql or .sql.gz files found in current directory.${NC}"
    exit 1
fi

# 3. Interactive Menu
echo "Available backups:"
echo ""
i=1
for file in "${sql_files[@]}"; do
    echo "  $i) $file"
    ((i++))
done
echo ""
echo "  q) Quit"
echo ""

read -p "Select file to restore: " choice

if [[ "$choice" =~ ^[qQ]$ ]]; then
    echo "Bye!"
    exit 0
fi

if [[ ! "$choice" =~ ^[0-9]+$ ]] || [ "$choice" -lt 1 ] || [ "$choice" -gt "${#sql_files[@]}" ]; then
    echo -e "${RED}Invalid selection.${NC}"
    exit 1
fi

# Adjust index (array is 0-based, choice is 1-based)
index=$((choice - 1))
SELECTED_FILE="${sql_files[$index]}"

echo ""
echo -e "You selected: ${BLUE}$SELECTED_FILE${NC}"
echo -e "${RED}WARNING: This will OVERWRITE database '$DBNAME'.${NC}"
read -p "Are you sure? (type 'yes' to confirm): " confirm

if [ "$confirm" != "yes" ]; then
    echo -e "${YELLOW}Operation cancelled.${NC}"
    exit 0
fi

# 4. Restore
echo -e "Restoring ${YELLOW}$SELECTED_FILE${NC} into ${YELLOW}$DBNAME${NC}..."

# We assume the backup contains DROP TABLE statements (if generated by our backup script)
# or that the user knows what they are doing.

RESTORE_SUCCESS=0
if [[ "$SELECTED_FILE" == *.gz ]]; then
    # Compressed file
    if gunzip -c "$SELECTED_FILE" | $mysqlbin $MYSQL_OPTS "$DBNAME"; then
        RESTORE_SUCCESS=1
    fi
else
    # Regular text file
    if $mysqlbin $MYSQL_OPTS "$DBNAME" < "$SELECTED_FILE"; then
        RESTORE_SUCCESS=1
    fi
fi

if [ $RESTORE_SUCCESS -eq 1 ]; then
    echo -e "${GREEN}Database restored successfully! ✅${NC}"
else
    echo -e "${RED}Error restoring database ❌${NC}"
    exit 1
fi
